### ISSUE TITLE
Broken / empty output cells in example notebooks 

### ISSUE THREAD

**Issue by abpolym** [biaslab/RxInfer.jl#10]
Many output cells in most [example notebooks](https://github.com/biaslab/RxInfer.jl/blob/main/examples) are empty/broken:

<img width="690" alt="emptycell" src="https://user-images.githubusercontent.com/8559692/199978993-41015fb6-177a-4efa-89a5-cb8fe177b215.png">

Fortunately, the output of the same notebooks is still present in the [docs](https://biaslab.github.io/RxInfer.jl/stable/examples/Autoregressive%20Model/):

<img width="880" alt="docs" src="https://user-images.githubusercontent.com/8559692/199979290-9305b52b-6a5c-4625-9732-e6bb23beeda0.png">

**Comment by Chengfeng-Jia** [comment]
And if you clone it from github to personal computer, these pictures will be present.

**Comment by Nimrais** [comment]
@abpolym Actually, It was appropriately done inside the documentation [here](https://biaslab.github.io/RxInfer.jl/stable/examples/overview/).

@albertpod @bvdmitri https://biaslab.github.io/RxInfer.jl/stable/examples/overview/ is not working.

**Comment by bvdmitri** [comment]
@abpolym  That is weird. The output is present locally and in the `nbviewer`: https://nbviewer.org/github/biaslab/RxInfer.jl/blob/main/examples/Autoregressive%20Model.ipynb.

@Nimrais yeah, it must be [https://biaslab.github.io/RxInfer.jl/stable/examples/Overview/](https://biaslab.github.io/RxInfer.jl/stable/examples/Overview/) with capital `O`. I'll take a look on it if I can fix it.

**Comment by bvdmitri** [comment]
The `overview` link should have been fixed here https://github.com/biaslab/RxInfer.jl/commit/c0e9b68de2a079dc4dbd9c7796fa006764e8f20a

**Comment by albertpod** [comment]
Subject to close?

**Comment by bvdmitri** [comment]
The output of notebooks is still broken, but AFAIK its an upstream issue of GitHub and Plots.jl. The output renders fine in the documentation

**Comment by albertpod** [comment]
Should we close this one?
