### ISSUE TITLE
`initmarginals` broadcasting not working for `PointMass`

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/RxInfer.jl#101]
It is possible to start of the inference procedure like 
```julia
inference(
	model = model(nr_samples),
	initmarginals = (z= NormalMeanVariance(0,1), ),
	data = (y = y, ),
)
```
which initializes all variables `z` with the `NormalMeanVariance(0,1)` distribution.
However, it throws an iteration error for `PointMass` objects, which need to be explicitly repeated as
```julia
inference(
	model = model(nr_samples),
	initmarginals = (z= repeat([PointMass(10)], nr_samples), ),
	data = (y = y, ),
)
```

**Comment by bvdmitri** [comment]
This task has been added to the [milestone](https://github.com/biaslab/RxInfer.jl/milestone/1) for tracking and prioritization.

**Comment by bvdmitri** [comment]
To solve this you simply need to add 
```
Base.broadcastable(pm::PointMass) = Ref(pm)
```

**Comment by bvdmitri** [comment]
@Chengfeng-Jia 
This task has been added to the [milestone](https://github.com/biaslab/RxInfer.jl/milestone/2) for tracking and prioritization.

**Comment by Chengfeng-Jia** [comment]
I tried running the following code,

```

inference(
	model = model(nr_samples),
	initmarginals = (z= PointMass(1.0), ),
	data = (y = y, ),
)
```
No error reported, should it have been fixed? Is there a mistake in my understanding

**Comment by bartvanerp** [comment]
@Chengfeng-Jia was `z` an array of random variables in your model? In this case the issue seems to have fixed itself.

**Comment by Chengfeng-Jia** [comment]
I misunderstood before, now I changed `z` to an array of random variables. Indeed, this code doesn't work.
`initmarginals = (z= PointMass(0),)`

However, if I change the code like this, it runs well and doesn't need to repeat
`initmarginals = (z= [PointMass(0)],)`

Do you think it's fine, or still need the broadcast part

**Comment by bartvanerp** [comment]
I would prefer `initmarginals = (z= PointMass(0),)` to work, similarly as we can do initmarginals = (z= Normal(0,1),)

**Comment by Chengfeng-Jia** [comment]
Uh, I see.

**Comment by bartvanerp** [comment]
Will be closed by https://github.com/biaslab/ReactiveMP.jl/pull/360
