### ISSUE TITLE
`warn` argument in `inference` function not affecting logs for unused vars

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/RxInfer.jl#104]
With `warn=false` set in the `inference` function, the inference function still prints warnings like:
```julia
Unused data variable has been found: 'y_61'. Ignore if 'y_61' has been used in deterministic nonlinear tranformation.
```

Adding to this:
- seems there is a typo in the warning: `tranformation` should be `transformation`.
- The `warn` argument is not present in the call signature in the `inference` docstring.

**Comment by albertpod** [comment]
ping @Chengfeng-Jia

**Comment by bvdmitri** [comment]
This task has been added to the [milestone](https://github.com/biaslab/RxInfer.jl/milestone/1) for tracking and prioritization.

**Comment by bvdmitri** [comment]
@Chengfeng-Jia 
This task has been added to the [milestone](https://github.com/biaslab/RxInfer.jl/milestone/2) for tracking and prioritization.
