### ISSUE TITLE
Docs need some proof reading

### ISSUE THREAD

**Issue by abpolym** [biaslab/RxInfer.jl#11]
I found a mention of ForneyLab in the docs as shown below:

<img width="951" alt="1" src="https://user-images.githubusercontent.com/8559692/200164395-58202c4e-44fe-4c37-af7b-f137dfa8e361.png">

I can imagine that reading through the docs will lead to discovery of more errors in the docs :)

**Comment by SebastianCallh** [comment]
There is also a mention of ReactiveMP in this section
https://biaslab.github.io/RxInfer.jl/stable/examples/Invertible%20Neural%20Network%20Tutorial/#Probabilistic-inference
