### ISSUE TITLE
AutoProposal in the SampleListFormConstraints works only for univariate distributions and logpdfs

### ISSUE THREAD

**Issue by bvdmitri** [biaslab/RxInfer.jl#117]
This must be changed https://github.com/biaslab/RxInfer.jl/blob/main/src/constraints/form/form_sample_list.jl#L46
Found by @ThijsvdLaar

**Comment by albertpod** [comment]
I've added a bug label; not sure whether it's an actual bug, more of an unsupported one.

**Comment by bvdmitri** [comment]
This should be fixed in #121
