### ISSUE TITLE
@constraints simply ignore incomplete factorization constraints without any warning

### ISSUE THREAD

**Issue by bvdmitri** [biaslab/RxInfer.jl#118]
The following code ignores the factorization constraints and does not give any warning
```julia
@constraints begin
    q(x)q(y)
    # should be q(x, y) = q(x)q(y) but no error or warning is shown
end
```
Found by @ThijsvdLaar

**Comment by bvdmitri** [comment]
ping @wouterwln , check that this bug is not present in the new version

**Comment by wouterwln** [comment]
@bvdmitri this throws an `UndefVarError` on q,  is that enough?

**Comment by bvdmitri** [comment]
We can throw a user-friendly error or something when we encounter smth which is unexpected (basically when not a single `@capture` captured the problematic expression)?

**Comment by wouterwln** [comment]
Coming back to this, I don't know if we can safely check if something is not captured by a single pipeline, since we do a postwalk over expressions and not over lines. A lot of expressions will not be captured by any pipeline. Any suggestions?

**Comment by bvdmitri** [comment]
I think the issue here is that `q(x)q(y)` is being transformed even though it first must a part of the `lhs_ = rhs_` expression and only then it can be transformed. `q(x)q(y)` by itself should not be transformed and should be just a function call to `q`. Or

**Comment by wouterwln** [comment]
That is exactly what happens, I could design an additional pipeline that triggers when it encounters a call to `q` that is not wrapped in a `lhs_ = rhs_` or `lhs_ :: rhs_` statement, but that seems a bit unsafe to me, don't you think?

**Comment by bvdmitri** [comment]
Yeah, it is unsafe, because there can a be a function named `q()`. So, technically a raw statement `q(x)q(y)` is not wrong, given that there is a global `q` function, the thing is that it works even if there is no global `q` function, which should simply throw `q is not defined` error IMO. 

I think you already know by yourself that less transformation we do in macros is better ;)

**Comment by wouterwln** [comment]
This is fixed in https://github.com/biaslab/GraphPPL.jl/pull/117. I throw an `ErrorException` for now. We can design a custom warning/error ad hoc
