### ISSUE TITLE
https//rxinfer.ml Certificate

### ISSUE THREAD

**Issue by abpolym** [biaslab/RxInfer.jl#12]
Firefox & Chrome cannot verify the certificate for the `https://rxinfer.ml` website and show a warning as below:

<img width="872" alt="4" src="https://user-images.githubusercontent.com/8559692/200166272-67695f9a-494a-465e-96b5-a1eab50625ae.png">

[More info from mozilla](https://support.mozilla.org/en-US/kb/error-codes-secure-websites?as=u&utm_source=inproduct)

**Comment by abpolym** [comment]
Seems like I just have to update the certificates - works on one PC (with correct & latest certificates issues 04.11.2022) but not on the other (older certificates issued ~2018)

**Comment by bvdmitri** [comment]
I have the same issue with the `Home` link in the header of the documentation, can you please check @abpolym on your side?

**Comment by bertdv** [comment]
here is teh email I got from my web hosting provider (versio.nl):

Hi Bert,
​
​Thank you for your message.
​
The A record for [rxinfer.ml](http://rxinfer.ml/). pointing to our redirect IP 185.182.56.12 was missing. The record is now created. Please wait 4-8 hours for the changes to propagate.

Please note a redirect only works with http://[rxinfer.ml](http://rxinfer.ml/) and not with httpS:// in our DNS panel.

​Feel free to get in touch if you have any further questions.

Met vriendelijke groet,
Fabien
Customer Support Engineer

**Comment by bertdv** [comment]
Got an answer from teh support desk:

Hi Bert,

If a browser forces the https:// connection visitors can see a warning instead of the redirect. It can only be solved if your link the domain to a hosting package and provide an SSL certificate for the domain. Then you can create the redirect through the redirect option on the hosting in DirectAdmin.

Met vriendelijke groet,
Fabien
Customer Support Engineer

**Comment by bertdv** [comment]
@bvdmitri @abpolym @albertpod not sure how to do that SSL stuff. Perhaps you know how to proceed?

**Comment by bvdmitri** [comment]
@bertdv @albertpod I think redirect should not be a problem if we setup a custom domain for github pages. Lets discuss on Monday.

**Comment by abpolym** [comment]
> I have the same issue with the `Home` link in the header of the documentation, can you please check @abpolym on your side?

Yeah it still is an issue on my side. I thought it was only an issue of older certificates for one of my local setups - but the with newer certificates and a fresh browser profile (no cookies remembering that I "accepted the risks") it shows me the initial warning prompt.

I have to look up how to proceed but [mozilla](https://support.mozilla.org/en-US/kb/error-codes-secure-websites?as=u&utm_source=inproduct) gives some good troubleshooting

**Comment by albertpod** [comment]
Can we close this one?

**Comment by bvdmitri** [comment]
Works as expected now
