### ISSUE TITLE
 initmarginals accept an array argument with different length

### ISSUE THREAD

**Issue by bvdmitri** [biaslab/RxInfer.jl#175]
`setmarginals!` from ReactiveMP uses `zip`, hence this 
```
initmarginals = (z= [NormalMeanVariance(0, 1)],)
```
Will initialize only the first `z` and skip the rest. We should use broadcasting instead

**Comment by bvdmitri** [comment]
@Nimrais 
This task has been added to the [milestone](https://github.com/biaslab/RxInfer.jl/milestone/3) for tracking and prioritization.

**Comment by Nimrais** [comment]
As I understand the issue at hand. 

But how do we want to resolve it?

```julia
initmarginals = (z= container,)
```
it should assign the marginal [NormalMeanVariance(0, 1)] to each random variable associated with the symbol z. On the other hand, if we use:

```julia
initmarginals = (z.=container,)
```

then it should assign each index of `z` to the aligned index in `container,` am I right?

**Comment by bvdmitri** [comment]
> each marginal associated with the symbol z to container itself

No, it should simply check that the lengths of `z` and the `container` match before calling `zip`.
See [here](https://github.com/biaslab/ReactiveMP.jl/blob/bdefc22917274917a8aec3f2d3a3af2de643270d/src/variables/variable.jl#L102). Please do the same for messages [here](https://github.com/biaslab/ReactiveMP.jl/blob/bdefc22917274917a8aec3f2d3a3af2de643270d/src/variables/variable.jl#L114)

> `initmarginals = (z.=container,)`

This syntax is not possible in Julia, we don't support it at all, so no need to do anything here
