### ISSUE TITLE
rxinference: `UndefVarError` on `historyvars = KeepEach()`

### ISSUE THREAD

**Issue by abpolym** [biaslab/RxInfer.jl#24]
```Julia
rxinference(
  [...]
  historyvars = KeepEach()
 [...]
)
```

causes the following error:

<img width="765" alt="fail" src="https://user-images.githubusercontent.com/8559692/203003998-a94856b8-aa3e-43cb-847b-1c2107a4b39e.png">

**Comment by bvdmitri** [comment]
Fixed in #25
