### ISSUE TITLE
Missing optimizer for discrete pointmass

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/RxInfer.jl#29]
Currently the `PointMass` constraint only works for continuous distributions. The optimizer for `Discrete` variables is missing, but it basically just is an `argmax` function. It is implemented in [0bd7aba](https://github.com/biaslab/RxInfer.jl/pull/20/commits/0bd7abad2cc20d06073776b2126a4c7c2553827f) of #20

**Comment by MagnusKoudahl** [comment]
Echoing this point for multivariate distributions, ex MvGaussians
