### ISSUE TITLE
Mathematical Equations in README

### ISSUE THREAD

**Issue by ludgerpaehler** [biaslab/RxInfer.jl#81]
The mathematical equations in the README are sadly not legible when using GitHub's dark mode. I.e. the equations are rendered in black, on a dark grey background.

**Comment by bvdmitri** [comment]
https://github.blog/2022-05-19-math-support-in-markdown/ looks like GitHub supports formulas now
Test
```math
y_i \sim \mathrm{Bernoulli}(\theta)
```
