### ISSUE TITLE
What's the difference between `initmarginals` and `priors`?

### ISSUE THREAD

**Issue by wmkouw** [biaslab/RxInfer.jl#95]
Some users have asked me what the difference between `initmarginals` and the prior distributions are, and whether they should be specified similarly.

1. This is more of a theoretical question than a software issue, but I think it's good to archive it here. Priors are part of the model (i.e., need to be specified in @model) and will always have to be specified in a probabilistic model. `initmarginals` is a consequence of the inference technique variational Bayes (VB). In VB, we need to specify a second probabilistic model `q` (often called the variational model or recognition model) that approximates the original model `p`. We optimize `q` such that it matches the posterior `p` as well as possible. It is an iterative optimization procedure, meaning you have a starting point and iterate through update equations. `initmarginals` defines the starting point. From a mathematical perspective, the initial marginals are only consequential if the objective function (i.e., free energy) is non-convex. From a software perspective, initializing the marginals can help ReactiveMP figure out which distributions to work with at which stage.

2. The initial marginals do not need to be specified exactly like the priors.

**Comment by MagnusKoudahl** [comment]
For didactic purposes, I think a lot of the confusion could be resolved by using the new constraints notation where `q` is denoted with circles on top of a regular FFG. That way there's a clear distinction between what's a prior (it's a square) and where it's specified and what's a posterior marginal (it's a circle) which naturally goes in a different place.

**Comment by bvdmitri** [comment]
I agree that the new diagrammatic notation will help to explain some concepts of our inference procedure, but I believe we shall wait for the actual publication first ;) In any case, we can discuss this issue on one of our next update meetings.

**Comment by bvdmitri** [comment]
Added in #173
