### ISSUE TITLE
Restructure examples in documentation

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/RxInfer.jl#97]
Following up on #94  and also our own observations about the documentation section, we need to restructure it. The idea is to split the example section into two (or more) subsections: `basic examples` and `advanced examples`, where the latter one includes the custom and more complicated nodes that we have designed over the years.

**Comment by albertpod** [comment]
ping @bartvanerp, I think we can proceed with the update. WDYT?

**Comment by bartvanerp** [comment]
Yes we should. Let's invest some time next week
